{% set name = "eemont" %}
{% set version = "0.3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 49f4c1f7e2ae432ec678875177619b1fed2e99017a810aa49a4c760fc0994ef0

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - beautifulsoup4
    - earthengine-api
    - ee_extra >=0.0.15
    - geopy
    - numpy
    - pandas
    - python >={{ python_min }}
    - python-box >=6.0.0
    - requests

test:
  requires:
    - python {{ python_min }}
  imports:
    - eemont

about:
  home: https://github.com/davemlz/eemont
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python package that extends Google Earth Engine
  doc_url: https://eemont.readthedocs.io/
  dev_url: https://github.com/davemlz/eemont

extra:
  recipe-maintainers:
    - davemlz
